Hw03 express
ivansinabdeev/nodejs-homework-02-06-REST-API pull request #2
Opened 2021-11-25 04:40 UTC by ivansinabdeev

Проверь пжлст, возможно нужно будет поправить)

2021-11-25 20:59 UTC, KirillKulakow commented on model/index.js
> -// const fs = require('fs/promises')
зачем тебе этот файл с методами?

2021-11-25 21:01 UTC, KirillKulakow requested changes
Need some fix

2021-11-28 15:28 UTC, ivansinabdeev commented
Пофиксил и отправил комит! :)

2021-11-28 21:42 UTC, KirillKulakow approved these changes

2021-12-02 22:09 UTC, merged