Hw04 auth
ivansinabdeev/nodejs-homework-02-06-REST-API pull request #3
Opened 2021-12-05 15:37 UTC by ivansinabdeev

проверь пжлст, в салке дополнения написал к этой ДЗ :)

2021-12-05 16:55 UTC, KirillKulakow commented on controllers/contacts/favorite.js
> +    const contact = await Contact.findByIdAndUpdate(
то есть я смогу внести изменения в контакт другого юзера?

2021-12-05 16:56 UTC, KirillKulakow commented on controllers/contacts/favorite.js
> +    const contact = await Contact.findByIdAndUpdate(
если узнаю ид этого контакта

2021-12-05 16:56 UTC, KirillKulakow commented on controllers/contacts/getById.js
> +    const contact = await Contact.findById(id);
я смогу найти любой контакт в базе, вне зависимости чей он

2021-12-05 16:57 UTC, KirillKulakow commented on controllers/contacts/removeById.js
> +    const contact = await Contact.findByIdAndRemove(id);
точно так же и с удалением

2021-12-05 17:02 UTC, KirillKulakow commented on controllers/contacts/updateById.js
> +    const contact = await Contact.findByIdAndUpdate(id, req.body, {
так же

2021-12-05 17:11 UTC, KirillKulakow commented on middlewares/authentication.js
> +    const [bearer, token] = req.headers.authorization.split(" ");
проверяй есть ли вообще поле authorization в headers

2021-12-05 17:12 UTC, KirillKulakow commented on middlewares/authentication.js
> +      // if (!user.token) {
зачем коммент?

2021-12-05 17:13 UTC, KirillKulakow requested changes
need fix

2021-12-06 01:23 UTC, ivansinabdeev commented
вроде пофиксил, жду проверки! :)

2021-12-06 19:06 UTC, KirillKulakow requested changes
One comment

2021-12-08 06:54 UTC, KirillKulakow approved these changes

2021-12-09 20:06 UTC, merged