Hw05 avatars
ivansinabdeev/nodejs-homework-02-06-REST-API pull request #4
Opened 2021-12-09 18:16 UTC by ivansinabdeev

Скорей всего нужны будут правки)

2021-12-09 20:08 UTC, KirillKulakow commented on controllers/users/signUp.js
> +    const avatarURL = gravatar.url("alex@gmail.com");
сюда пишется имейл пользователя

2021-12-09 20:13 UTC, KirillKulakow commented on controllers/users/updateAvatar.js
> +        req.body,
кажется req.body лишнее

2021-12-09 20:14 UTC, KirillKulakow requested changes
need some fix

2021-12-10 00:47 UTC, ivansinabdeev commented
пофиксил)

2021-12-10 06:02 UTC, KirillKulakow approved these changes

2021-12-11 10:22 UTC, merged